development:
  adapter: mysql
  database: heisenbase
  host: localhost
  username: root
  password:
  socket: /tmp/mysql.sock
  pool: 5
  timeout: 5000
production:
  adapter: mysql
  database: <%= ENV['DATABASE_NAME'] %>
  host: <%= ENV['DATABASE_HOSTNAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
  timeout: 5000
