development:
  adapter: mysql
  database: heisenbase
  hostname: localhost
  username: root
  password:
  socket: /tmp/mysql.sock
  pool: 5
  timeout: 5000
production:
  url: <%= ENV['DATABASE_URL'] %>
